org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17.13

mod_version=1.5.35-26.1.2
maven_group=fishmod
archives_base_name=FishModDungeons

fabric_version=0.154.2+26.1.2
fabric_kotlin_version=1.13.10+kotlin.2.3.20
modmenu_version=18.0.0-beta.1
hypixel_api_version=1.0.2+build.1+mc26.1
hypixel_api_core_version=1.0.2

modrinth_project_id=7dRE7dga
modrinth_version=1.0.0-26.1.2-dungeons
