package fishmod.features.pv.tabs.inv

import fishmod.features.croesus.LootIcons
import fishmod.utils.networth.ItemsDb
import net.minecraft.world.item.Item
import net.minecraft.world.item.ItemStack
import net.minecraft.world.item.Items

// Sack item id -> owning sack + display icon.
object SackTable {
    val ORDER = listOf(
        "Agronomy", "Garden", "Husbandry", "Mining", "Dwarven Mines", "Crystal Hollows", "Gemstone", "Combat", "Slayer",
        "Dungeon", "Dragon", "Foraging", "Fishing", "Lava Fishing", "Trophy Fish", "Trophy Frog", "Nether", "Rift",
        "Runes", "Candy", "Winter", "Enchanted", "Other",
    )

    private fun s(v: String) = v.split(' ').filter { it.isNotEmpty() }.toSet()

    private val TABLE: Map<String, Set<String>> = linkedMapOf(
        "Agronomy" to s("WHEAT SEEDS HAY_BLOCK CARROT_ITEM POTATO_ITEM POISONOUS_POTATO PUMPKIN MELON SUGAR_CANE INK_SACK:3 CACTUS NETHER_STALK RED_MUSHROOM BROWN_MUSHROOM DOUBLE_PLANT MOONFLOWER WILD_ROSE GOLDEN_CARROT"),
        "Garden" to s("COMPOST CROPIE SQUASH FERMENTO HELIANTHUS BOX_OF_SEEDS POLISHED_PUMPKIN TIGHTLY_TIED_HAY_BALE AGARIMOO_TONGUE BIOFUEL OIL_BARREL JACOBS_TICKET CONDENSED_WATER_LILY DUNG HONEY_JAR JELLY PLANT_MATTER CHEESE_FUEL FINE_FLOUR CHILI_PEPPER DEAD_PLANT MELON_JUICE CARROT_ZEST BOTROOT CACTUS_FLOWER SALTED_SUNFLOWER_SEEDS CORNUCOPIA CANE_KNOT DEEPFRIES FEASTFUNGUS PUFFERCLOUD PLANTBOY_ADVANCE ASHWREATH CHOCONUT GLOOMGOURD LONELILY SHADEVINE CREAMBLOOM DUSKBLOOM SOGGYBUD CINDERSHADE SCOURROOT TURTLELLINI VEILSHROOM BLASTBERRY DO_NOT_EAT_SHROOM FLESHTRAP COALROOT THORNSHADE NOCTILUME ZOMBUD SNOOZLING CHLORONITE THUNDERLING GLOWING_MUSHROOM GODSEED CHEESEBITE SHELLFRUIT WITHERBLOOM STOPLIGHT_PETAL PHANTOMLEAF DEVOURER STARTLEVINE ALL_IN_ALOE TIMESTALK GLASSCORN MAGIC_JELLYBEAN ETHEREAL_VINE COMPACTED_MOONFLOWER COMPACTED_SUNFLOWER COMPACTED_WILD_ROSE"),
        "Husbandry" to s("RAW_CHICKEN FEATHER EGG RAW_BEEF LEATHER PORK MUTTON WOOL RABBIT RABBIT_FOOT RABBIT_HIDE HONEYCOMB"),
        "Mining" to s("COBBLESTONE STONE COAL IRON_INGOT GOLD_INGOT DIAMOND INK_SACK:4 REDSTONE EMERALD QUARTZ OBSIDIAN GLOWSTONE_DUST GRAVEL FLINT SAND SAND:1 ENDER_STONE ICE PACKED_ICE SNOW_BALL SNOW_BLOCK NETHERRACK MYCEL"),
        "Dwarven Mines" to s("MITHRIL_ORE TITANIUM_ORE HARD_STONE STARFALL TREASURITE REFINED_MINERAL GLOSSY_GEMSTONE CONCENTRATED_STONE GLACITE UMBER TUNGSTEN GLACITE_JEWEL TUNGSTEN_KEY UMBER_KEY SORROW VOLTA PLASMA BOB_OMB"),
        "Crystal Hollows" to s("GOBLIN_EGG GOBLIN_EGG_BLUE GOBLIN_EGG_GREEN GOBLIN_EGG_RED GOBLIN_EGG_YELLOW WISHING_COMPASS JUNGLE_KEY CONTROL_SWITCH ELECTRON_TRANSMITTER FTX_3070 ROBOTRON_REFLECTOR SYNTHETIC_HEART SUPERLITE_MOTOR YOGGIE OIL_BARREL"),
        "Combat" to s("ROTTEN_FLESH BONE STRING SPIDER_EYE SULPHUR ENDER_PEARL GHAST_TEAR SLIME_BALL BLAZE_ROD MAGMA_CREAM MITE_GEL CRYSTAL_FRAGMENT ANCIENT_CLAW GRIFFIN_FEATHER KISMET_FEATHER MYTHOS_FRAGMENT ECTOPLASM SPOOKY_SHARD PUMPKIN_GUTS WEREWOLF_SKIN SPECTRE_DUST TENTACLE_MEAT CHUM BLUE_SHARK_TOOTH NURSE_SHARK_TOOTH TIGER_SHARK_TOOTH SHARK_FIN ABSOLUTE_ENDER_PEARL GAZING_PEARL"),
        "Slayer" to s("REVENANT_FLESH REVENANT_VISCERA UNDEAD_CATALYST REVENANT_CATALYST FOUL_FLESH TARANTULA_WEB TARANTULA_SILK TARANTULA_CATALYST SPIDER_CATALYST TOXIC_ARROW_POISON TWILIGHT_ARROW_POISON WOLF_TOOTH GOLDEN_TOOTH NULL_SPHERE NULL_ATOM NULL_OVOID SPIDER_EGG DERELICT_ASHE WITHER_CATALYST CORRUPTED_FRAGMENT"),
        "Dungeon" to s("DUNGEON_TRAP DUNGEON_DECOY SUPERBOOM_TNT INFLATABLE_JERRY SPIRIT_LEAP HEALING_TISSUE ARCHITECT_FIRST_DRAFT DUNGEON_CHEST_KEY MIMIC_FRAGMENT BONZO_FRAGMENT SCARF_FRAGMENT THORN_FRAGMENT LIVID_FRAGMENT GIANT_FRAGMENT_BIGFOOT GIANT_FRAGMENT_BOULDER GIANT_FRAGMENT_LASER GIANT_FRAGMENT_DIAMOND GIANT_FRAGMENT_BOULDER FEL_PEARL GOLEM_POPPY RITUAL_RESIDUE WITHER_SOUL ENDER_PEARL_DUNGEON KISMET_FEATHER"),
        "Dragon" to s("SUMMONING_EYE REMNANT_OF_THE_EYE OLD_FRAGMENT STRONG_FRAGMENT WISE_FRAGMENT UNSTABLE_FRAGMENT YOUNG_FRAGMENT SUPERIOR_FRAGMENT PROTECTOR_FRAGMENT HOLY_FRAGMENT RITUAL_RESIDUE"),
        "Foraging" to s("LOG LOG:1 LOG:2 LOG:3 LOG_2 LOG_2:1 SAPLING SAPLING:1 SAPLING:2 SAPLING:3 SAPLING:4 SAPLING:5 APPLE MANGROVE_LOG FIG_LOG CHERRY_LOG HELIX_LOG TENDER_WOOD VINESAP FIGSTONE MANGCORE LUSHLILAC BAMBOO STICK DEEP_ROOT STRETCHING_STICKS HELIXIS HEMOVIBE HEMOGLASS RUBY_VEILSHROOM VEILSHROOM_BUNCH FLORAL_GELATIN AGATHA_COUPON MIRIA_COUPON MIRIA_PRIZE STARLYN_PRIZE CRUNCHY_BUG SHIELD_DUST"),
        "Fishing" to s("RAW_FISH RAW_FISH:1 RAW_FISH:2 RAW_FISH:3 PRISMARINE_SHARD PRISMARINE_CRYSTALS CLAY_BALL WATER_LILY INK_SACK SPONGE SEA_LUMIES GILL_MEMBRANE STURDY_BONE WET_WATER CAN_OF_WORMS TORN_CLOTH RUSTY_COIN BUSTED_BELT_BUCKLE OLD_LEATHER_BOOT FROGCOIN SEARED_ESCARGOT WORM_MEMBRANE DIVER_FRAGMENT FISHY_TREAT"),
        "Lava Fishing" to s("MAGMA_FISH MAGMA_FISH_SILVER MAGMA_FISH_GOLD MAGMA_FISH_DIAMOND LAVA_SHELL LUMP_OF_MAGMA PYROCLASTIC_SCALE MOOGMA_PELT FLAMING_HEART SCORCHED_CRAB_STICK FRIED_FEATHER THUNDER_SHARDS ORB_OF_ENERGY CUP_OF_BLOOD HORN_OF_TAURUS SINGED_POWDER"),
        "Nether" to s("SULPHUR_ORE BLAZE_ASHES MUTATED_BLAZE_ASHES MILLENIA_OLD_BLAZE_ASHES MAGMA_CHUNK MAGMAG LEATHER_CLOTH SPELL_POWDER KADA_LEAD BEZOS COMPACT_OOZE REKINDLED_EMBER_FRAGMENT KUUDRA_TEETH CORRUPTED_NETHER_STAR HALLOWED_SKULL BURNING_EYE DIGESTED_MUSHROOMS HALF_EATEN_MUSHROOM LUMINO_FIBER HEAVY_PEARL WHIPPED_MAGMA_CREAM FLAMES CRUDE_GABAGOOL CRUDE_GABAGOOL_DISTILLATE BLAZE_ROD_DISTILLATE SULPHURIC_COAL MATCH_STICKS VOLCANIC_ROCK GAZING_PEARL SCORCHED_POWER_CRYSTAL TOKEN_OF_THE_CENTURY"),
        "Rift" to s("FESTERING_FLY FUNNY_BONE JAWBREAKER BRITTLE_POWDER SPELL_SOOT SMOLDERING_EMBERS DIRTY_FINGERNAILS FROG_LEGS PIXIE_DUST ROTTED_LEAF RUFFLED_FEATHER WATERBORNE_LICE WARMED_FLAKES NEVER_MELT_ICE GELATINOUS_GLOOP VOID_OOZE CONSOLE_PANEL ALL_IN_ALOE_FRAGMENT SLUDGE_JUICE PRECURSOR_APPARATUS ASCENSION_ROPE SUSPICIOUS_SCRAP ALLIGATOR_SKIN BRONZE_BOWL BLUE_RING BROKEN_RADAR SILVER_FANG CRYSTALIZED_MOONLIGHT CORLEONITE"),
        "Candy" to s("GREEN_CANDY PURPLE_CANDY DARK_CANDY ECTOPLASM PUMPKIN_GUTS SPOOKY_SHARD WEREWOLF_SKIN SOUL_FRAGMENT CARNIVAL_TICKET"),
        "Winter" to s("WHITE_GIFT GREEN_GIFT RED_GIFT PARTY_GIFT ICE_HUNK BLUE_ICE_HUNK GLACIAL_FRAGMENT WALNUT ENCHANTED_ICE ENCHANTED_PACKED_ICE ENCHANTED_SNOW_BLOCK"),
    )

    private val BY_ID: Map<String, String> = HashMap<String, String>().also { m -> for ((k, v) in TABLE) for (id in v) m.putIfAbsent(id, k) }
    private val TROPHY = Regex("_(BRONZE|SILVER|GOLD|DIAMOND)$")
    private val FROG = Regex("FROG|PUDDLE_JUMPER|REALITY_HOPPER|LOTUS")

    fun sackOf(id: String): String {
        BY_ID[id]?.let { return it }
        return when {
            id.startsWith("RUNE_") -> "Runes"
            id.endsWith("_GEM") -> "Gemstone"
            id.startsWith("LOTUS") || (TROPHY.containsMatchIn(id) && FROG.containsMatchIn(id)) -> "Trophy Frog"
            TROPHY.containsMatchIn(id) -> "Trophy Fish"
            id.startsWith("ENCHANTED_") || id.startsWith("COMPACTED_") || id.startsWith("MUTANT_") -> "Enchanted"
            id.endsWith("_FRAGMENT") -> "Dungeon"
            else -> "Other"
        }
    }

    // Icons: null cached only once the items DB has loaded.
    private val icons = HashMap<String, ItemStack>()
    private val PAPER by lazy { ItemStack(Items.PAPER) }

    private val VARIANTS: Map<String, Item> by lazy {
        mapOf(
            "LOG" to Items.OAK_LOG, "LOG:1" to Items.SPRUCE_LOG, "LOG:2" to Items.BIRCH_LOG, "LOG:3" to Items.JUNGLE_LOG,
            "LOG_2" to Items.ACACIA_LOG, "LOG_2:1" to Items.DARK_OAK_LOG,
            "SAPLING" to Items.OAK_SAPLING, "SAPLING:1" to Items.SPRUCE_SAPLING, "SAPLING:2" to Items.BIRCH_SAPLING,
            "SAPLING:3" to Items.JUNGLE_SAPLING, "SAPLING:4" to Items.ACACIA_SAPLING, "SAPLING:5" to Items.DARK_OAK_SAPLING,
            "RAW_FISH" to Items.COD, "RAW_FISH:1" to Items.SALMON, "RAW_FISH:2" to Items.TROPICAL_FISH, "RAW_FISH:3" to Items.PUFFERFISH,
            "SAND:1" to Items.RED_SAND, "MANGROVE_LOG" to Items.MANGROVE_LOG, "CHERRY_LOG" to Items.CHERRY_LOG,
            "DOUBLE_PLANT" to Items.SUNFLOWER, "MYCEL" to Items.MYCELIUM, "HAY_BLOCK" to Items.HAY_BLOCK,
        )
    }

    fun icon(id: String): ItemStack {
        icons[id]?.let { return it }
        val st: ItemStack? = VARIANTS[id]?.let { ItemStack(it) }
            ?: when {
                id.startsWith("RUNE_") -> LootIcons.icon("RUNE")
                id.startsWith("LOTUS") || (TROPHY.containsMatchIn(id) && FROG.containsMatchIn(id)) -> ItemStack(Items.FROGSPAWN)
                TROPHY.containsMatchIn(id) && ItemsDb.get(id) == null -> LootIcons.icon(id.replace(TROPHY, "")) ?: ItemStack(Items.TROPICAL_FISH)
                else -> LootIcons.icon(id)
            }
        if (st != null) { icons[id] = st; return st }
        if (ItemsDb.isLoaded()) { icons[id] = PAPER }
        return PAPER
    }

    fun name(id: String): String {
        runCatching { ItemsDb.get(id)?.get("name")?.asString }.getOrNull()?.let { return it.replace(Regex("§."), "") }
        val m = TROPHY.find(id)
        val base = if (m != null) id.removeSuffix(m.value) else id
        val pretty = base.replace(':', ' ').split('_').filter { it.isNotEmpty() }.joinToString(" ") { it.lowercase().replaceFirstChar(Char::uppercase) }
        return if (m != null) "$pretty (${m.groupValues[1].lowercase().replaceFirstChar(Char::uppercase)})" else pretty
    }
}
