package fishmod.features.pv.tabs.skills

// Generated from NEU-REPO constants/attribute_shards.json.
internal class AttrDef(val id: String, val shard: String, val name: String, val ability: String, val rarity: String, val code: String)

internal object AttrData {
    // Cumulative shards needed per level (1..10), by rarity.
    val LEVELS: Map<String, IntArray> = mapOf(
        "COMMON" to intArrayOf(1, 4, 9, 15, 22, 30, 40, 54, 72, 96),
        "UNCOMMON" to intArrayOf(1, 3, 6, 10, 15, 21, 28, 36, 48, 64),
        "RARE" to intArrayOf(1, 3, 6, 9, 13, 17, 22, 28, 36, 48),
        "EPIC" to intArrayOf(1, 2, 4, 6, 9, 12, 16, 20, 25, 32),
        "LEGENDARY" to intArrayOf(1, 2, 3, 5, 7, 9, 12, 15, 19, 24),
    )
    val ALL: Array<AttrDef> = arrayOf(
        AttrDef("nature_elemental", "grove", "Grove", "Nature Elemental", "COMMON", "C1"),
        AttrDef("fog_elemental", "mist", "Mist", "Fog Elemental", "COMMON", "C2"),
        AttrDef("light_elemental", "flash", "Flash", "Light Elemental", "COMMON", "C3"),
        AttrDef("nocturnal_animal", "phanpyre", "Phanpyre", "Nocturnal Animal", "COMMON", "C4"),
        AttrDef("cheapstake", "cod", "Cod", "Cheapstake", "COMMON", "C5"),
        AttrDef("animal_resistance", "howling_spirit", "Howling Spirit", "Animal Resistance", "COMMON", "C6"),
        AttrDef("moonglade_mastery", "phanflare", "Phanflare", "Moonglade Mastery", "COMMON", "C7"),
        AttrDef("aquatic_resistance", "dumpster_diver", "Dumpster Diver", "Aquatic Resistance", "COMMON", "C8"),
        AttrDef("experience", "lapis_zombie", "Lapis Zombie", "Experience", "COMMON", "C9"),
        AttrDef("mossy_box", "hideonleaf", "Hideonleaf", "Mossy Box", "COMMON", "C10"),
        AttrDef("forest_fishing", "verdant", "Verdant", "Forest Fishing", "COMMON", "C11"),
        AttrDef("skeletal_ruler", "chill", "Chill", "Skeletal Ruler", "COMMON", "C12"),
        AttrDef("fortunate_farmer", "fly", "Fly", "Fortunate Farmer", "COMMON", "C13"),
        AttrDef("hunter", "sea_archer", "Bogged", "Creature Fisher", "COMMON", "C14"),
        AttrDef("arachno_resistance", "voracious_spider", "Voracious Spider", "Arthropod Resistance", "COMMON", "C15"),
        AttrDef("happy_box", "hideongift", "Hideongift", "Happy Box", "COMMON", "C16"),
        AttrDef("yummy", "birries", "Birries", "Yummy", "COMMON", "C17"),
        AttrDef("undead_resistance", "tank_zombie", "Tank Zombie", "Undead Resistance", "COMMON", "C18"),
        AttrDef("fig_sharpening", "crow", "Crow", "Fig Sharpening", "COMMON", "C19"),
        AttrDef("unity_is_strength", "tadgang", "Tadgang", "Unity is Strength", "COMMON", "C20"),
        AttrDef("ender_resistance", "zealot", "Zealot", "Ender Resistance", "COMMON", "C21"),
        AttrDef("hitman_cooldown", "rabbit_mafioso", "Rabbit Mafioso", "Hitman Cooldown", "COMMON", "C22"),
        AttrDef("bucket_lover", "coralot", "Coralot", "Bucket Lover", "COMMON", "C23"),
        AttrDef("tree_lurker", "harpy", "Harpy", "Tree Lurker", "COMMON", "C24"),
        AttrDef("visitor_bait", "mudworm", "Mudworm", "Visitor Speed", "COMMON", "C25"),
        AttrDef("lotus_trophy", "lotus_fish", "Lotusfish", "Lotus Trophy", "COMMON", "C26"),
        AttrDef("midas_touch", "golden_ghoul", "Golden Ghoul", "Midas Touch", "COMMON", "C27"),
        AttrDef("crop_speed", "locust", "Locust", "Crop Speed", "COMMON", "C28"),
        AttrDef("forest_strength", "azure", "Azure", "Forest Strength", "COMMON", "C29"),
        AttrDef("blazing_resistance", "bezal", "Bezal", "Blazing Resistance", "COMMON", "C30"),
        AttrDef("woodland_resistance", "stag_beetle", "Stag Beetle", "Woodland Resistance", "COMMON", "C31"),
        AttrDef("fisherman", "night_squid", "Inkling", "Fisherman", "COMMON", "C32"),
        AttrDef("yog_membrane", "yog", "Yog", "Yog Membrane", "COMMON", "C33"),
        AttrDef("owl_friend", "boreal_owl", "Boreal Owl", "Owl Friend", "COMMON", "C34"),
        AttrDef("decent_karma", "newt", "Newt", "Decent Karma", "COMMON", "C35"),
        AttrDef("rotten_pickaxe", "miner_zombie", "Miner Zombie", "Rotten Pickaxe", "COMMON", "C36"),
        AttrDef("fortunate_miner", "flitter", "Flitter", "Fortunate Miner", "COMMON", "C37"),
        AttrDef("lake_fishing", "tepid", "Tepid", "Lake Fishing", "COMMON", "C38"),
        AttrDef("mythological_resistance", "cretan_bull", "Cretan Bull", "Mythological Resistance", "COMMON", "C39"),
        AttrDef("queen_tracker", "ant", "Ant", "Queen Tracker", "COMMON", "C40"),
        AttrDef("cave_fishing", "cavernfish", "Cavernfish", "Cave Fishing", "COMMON", "C41"),
        AttrDef("frozen_resistance", "strongarm", "Strongarm", "Frozen Resistance", "COMMON", "C42"),
        AttrDef("gold_box", "hideonsun", "Hideonsun", "Gold Box", "COMMON", "C43"),
        AttrDef("skeletal_resistance", "haggard", "Haggard", "Skeletal Resistance", "COMMON", "C44"),
        AttrDef("honey_speed", "honeyhog", "Honeyhog", "Honey Speed", "COMMON", "C45"),
        AttrDef("subterranean_resistance", "shyworm", "Shyworm", "Subterranean Resistance", "COMMON", "C46"),
        AttrDef("arcane_resistance", "brineling", "Brineling", "Arcane Resistance", "COMMON", "C47"),
        AttrDef("rabbit_youth", "chocobun", "Chocobun", "Rabbit Youth", "COMMON", "C48"),
        AttrDef("foraging_speed", "foxtrot", "Foxtrot", "Foraging Speed", "COMMON", "C49"),
        AttrDef("torrhus_mastery", "firefox", "Firefox", "Torrhus Mastery", "COMMON", "C52"),
        AttrDef("diurnal_animal", "groundhog", "Groundhog", "Diurnal Animal", "COMMON", "C55"),
        AttrDef("torrhus_diver", "timil", "Timil", "Torrhus Diver", "COMMON", "C56"),
        AttrDef("airborne_resistance", "blue_jay", "Blue Jay", "Airborne Resistance", "COMMON", "C58"),
        AttrDef("chocolate_speed", "bunbun", "Bunbun", "Chocolate Speed", "COMMON", "C61"),
        AttrDef("honey_haul", "honeybuzz", "Honeybuzz", "Honey Haul", "COMMON", "C64"),
        AttrDef("honey_luck", "pollendart", "Pollendart", "Honey Luck", "COMMON", "C67"),
        AttrDef("earth_elemental", "terra", "Terra", "Earth Elemental", "EPIC", "E1"),
        AttrDef("frost_elemental", "cryo", "Cryo", "Frost Elemental", "EPIC", "E2"),
        AttrDef("wind_elemental", "aero", "Aero", "Wind Elemental", "EPIC", "E3"),
        AttrDef("foraging_wisdom", "pandarai", "Pandarai", "Foraging Wisdom", "EPIC", "E4"),
        AttrDef("excellent_karma", "leviathan", "Leviathan", "Excellent Karma", "EPIC", "E5"),
        AttrDef("echo_of_resistance", "alligator", "Alligator", "Echo of Resistance", "EPIC", "E6"),
        AttrDef("berry_mogul", "fenlord", "Fenlord", "Berry Mogul", "EPIC", "E7"),
        AttrDef("pickaxe_cooldown", "abyssal_miner", "Abyssal Miner", "Pickaxe Cooldown", "EPIC", "E8"),
        AttrDef("hunters_suppress", "basilisk", "Basilisk", "Hunter's Suppress", "EPIC", "E9"),
        AttrDef("echo_of_atomized", "iguana", "Iguana", "Echo of Atomized", "EPIC", "E10"),
        AttrDef("lucky_rod", "moray_eel", "Moray Eel", "Lucky Rod", "EPIC", "E11"),
        AttrDef("special_upgrades", "special_zealot", "Special Zealot", "Special Upgrades", "EPIC", "E12"),
        AttrDef("lunar_power", "lunar_moth", "Lunar Moth", "Lunar Power", "EPIC", "E13"),
        AttrDef("trophy_hunter", "fire_eel", "Fire Eel", "Trophy Hunter", "EPIC", "E14"),
        AttrDef("deep_technique", "bal", "Bal", "Deep Technique", "EPIC", "E15"),
        AttrDef("sack_size", "hideonsack", "Hideonsack", "Sack Size", "EPIC", "E16"),
        AttrDef("fishing_speed", "water_hydra", "Water Hydra", "Fishing Speed", "EPIC", "E17"),
        AttrDef("blazing", "flare", "Flare", "Infernal Ruler", "EPIC", "E18"),
        AttrDef("sky_high", "murderwing", "Murderwing", "Sky High", "EPIC", "E19"),
        AttrDef("fishing_experience", "sea_emperor", "Loch Emperor", "Sea Wisdom", "EPIC", "E20"),
        AttrDef("reborn", "prince", "Prince", "Reborn", "EPIC", "E21"),
        AttrDef("echo_of_essence", "komodo_dragon", "Komodo Dragon", "Echo of Essence", "EPIC", "E22"),
        AttrDef("outstanding_fisher", "blue_crab", "Blue Crab", "Outstanding Fisher", "EPIC", "E23"),
        AttrDef("faker", "mimic", "Mimic", "Faker", "EPIC", "E24"),
        AttrDef("slayer_progress", "wolverine", "Wolverine", "Slayer Progress", "EPIC", "E25"),
        AttrDef("shell", "shellwise", "Shellwise", "Shell", "EPIC", "E26"),
        AttrDef("warrior", "barbarian_duke_x", "Barbarian Duke X", "Warrior", "EPIC", "E27"),
        AttrDef("why_not_more", "toucan", "Toucan", "Why Not More", "EPIC", "E28"),
        AttrDef("echo_of_ruler", "caiman", "Caiman", "Echo of Ruler", "EPIC", "E30"),
        AttrDef("solar_power", "firefly", "Firefly", "Solar Power", "EPIC", "E31"),
        AttrDef("echo_of_hunter", "sea_serpent", "Sea Serpent", "Echo of Hunter", "EPIC", "E32"),
        AttrDef("veil", "ghost", "Ghost", "Veil", "EPIC", "E33"),
        AttrDef("mana_regeneration", "xyz", "XYZ", "Mana Regeneration", "EPIC", "E34"),
        AttrDef("hunt_wisdom", "leatherback", "Leatherback", "Hunt Wisdom", "EPIC", "E35"),
        AttrDef("cavern_wisdom", "cavernshade", "Cavernshade", "Cavern Wisdom", "EPIC", "E36"),
        AttrDef("garden_wisdom", "dragonfly", "Dragonfly", "Garden Wisdom", "EPIC", "E37"),
        AttrDef("big_game_hunter", "sphinx", "Sphinx", "Mythological Tracker", "EPIC", "E39"),
        AttrDef("king_of_greed", "king_minos", "King Minos", "King of Greed", "EPIC", "E42"),
        AttrDef("ghastly_distraction", "dive_ghast", "Dive Ghast", "Ghastly Distraction", "EPIC", "E43"),
        AttrDef("foragers_fortune", "silkbreeze", "Silkbreeze", "Forager's Fortune", "EPIC", "E44"),
        AttrDef("devouring_spread", "gemzie", "Gemzie", "Devouring Spread", "EPIC", "E45"),
        AttrDef("divine_rabbit_luck", "rabbit_godmother", "Rabbit Godmother", "Divine Rabbit Luck", "EPIC", "E46"),
        AttrDef("fishers_fortune", "giant_isopod", "Giant Isopod", "Fisher's Fortune", "EPIC", "E47"),
        AttrDef("attack_speed", "burningsoul", "Inferno Demonlord", "Attack Speed", "EPIC", "E48"),
        AttrDef("honey_refill", "queen_bee", "Queen Bee", "Honey Refill", "EPIC", "E49"),
        AttrDef("catacombs_explorer", "bonzo", "Bonzo", "Catacombs Explorer", "EPIC", "E51"),
        AttrDef("lathering_greed", "beeheemoth", "Beeheemoth", "Lathering Greed", "EPIC", "E52"),
        AttrDef("catacombs_graduate", "scarf", "Scarf", "Catacombs Graduate", "EPIC", "E54"),
        AttrDef("dominance", "thorn", "Thorn", "Dominance", "EPIC", "E57"),
        AttrDef("social_wisdom", "mountain_goat", "Mountain Goat", "Social Wisdom", "EPIC", "E58"),
        AttrDef("glossy_fortune", "scatha", "Scatha", "Glossy Fortune", "EPIC", "E60"),
        AttrDef("royal_riches", "nilbog", "Nilbog", "Royal Riches", "EPIC", "E63"),
        AttrDef("freezing_spread", "littlefoot", "Littlefoot", "Freezing Spread", "EPIC", "E66"),
        AttrDef("shadow_elemental", "tenebris", "Tenebris", "Shadow Elemental", "LEGENDARY", "L1"),
        AttrDef("snow_elemental", "blizzard", "Blizzard", "Snow Elemental", "LEGENDARY", "L2"),
        AttrDef("storm_elemental", "tempest", "Tempest", "Storm Elemental", "LEGENDARY", "L3"),
        AttrDef("reptiloid", "chameleon", "Chameleon", "Reptiloid", "LEGENDARY", "L4"),
        AttrDef("loch_hook", "nessie", "Nessie", "Loch Hook", "LEGENDARY", "L5"),
        AttrDef("echo_of_echoes", "tiamat", "Tiamat", "Echo of Echoes", "LEGENDARY", "L6"),
        AttrDef("echo_of_wisdom", "wyvern", "Wyvern", "Echo of Wisdom", "LEGENDARY", "L7"),
        AttrDef("cloak_improvement", "tortoise", "Tortoise", "Cloak Improvement", "LEGENDARY", "L8"),
        AttrDef("fortitude", "endstone_protector", "End Stone Protector", "Unlimited Fortitude", "LEGENDARY", "L9"),
        AttrDef("egg_finder", "rabbit_godfather", "Rabbit Godfather", "Egg Finder", "LEGENDARY", "L10"),
        AttrDef("charmed", "naga", "Naga", "Charmed", "LEGENDARY", "L11"),
        AttrDef("book_wisdom", "lapis_creeper", "Lapis Creeper", "Book Wisdom", "LEGENDARY", "L12"),
        AttrDef("wart_eater", "wartybug", "Wartybug", "Wart Eater", "LEGENDARY", "L13"),
        AttrDef("payback", "spike", "Spike", "Payback", "LEGENDARY", "L14"),
        AttrDef("mending", "kraken", "Kraken", "Vitality", "LEGENDARY", "L15"),
        AttrDef("maximal_torment", "taurus", "Taurus", "Unlimited Torment", "LEGENDARY", "L17"),
        AttrDef("pity", "daemon", "Daemon", "Pity", "LEGENDARY", "L18"),
        AttrDef("star_bait", "moltenfish", "Moltenfish", "Star Bait", "LEGENDARY", "L20"),
        AttrDef("echo_of_tracking", "doomspiral", "Doomspiral", "Echo of Tracking", "LEGENDARY", "L21"),
        AttrDef("splendor", "macaw", "Macaw", "Splendor", "LEGENDARY", "L22"),
        AttrDef("life_regeneration", "shinyfish", "Shinyfish", "Help From Above", "LEGENDARY", "L23"),
        AttrDef("wings_of_destiny", "ananke", "Ananke", "Wings of Destiny", "LEGENDARY", "L24"),
        AttrDef("tuning_box", "hideonbox", "Hideonbox", "Tuning Box", "LEGENDARY", "L25"),
        AttrDef("double_hook", "lord_jawbus", "Lord Jawbus", "Crimson Hook", "LEGENDARY", "L26"),
        AttrDef("matriarch_cubs", "hellwisp", "Hellwisp", "Matriarch Cubs", "LEGENDARY", "L27"),
        AttrDef("magic_find", "cinder_bat", "Cinderbat", "Magic Find", "LEGENDARY", "L28"),
        AttrDef("hunter_karma", "megalith", "Megalith", "Hunter's Karma", "LEGENDARY", "L29"),
        AttrDef("elite", "power_dragon", "Power Dragon", "Elite", "LEGENDARY", "L30"),
        AttrDef("pet_wisdom", "condor", "Condor", "Pet Wisdom", "LEGENDARY", "L31"),
        AttrDef("starborn", "sun_fish", "Sun Fish", "Starborn", "LEGENDARY", "L32"),
        AttrDef("veteran", "apex_dragon", "Apex Dragon", "Veteran", "LEGENDARY", "L33"),
        AttrDef("rare_bird", "dodo", "Dodo", "Tracking", "LEGENDARY", "L34"),
        AttrDef("queenly_echo", "queen_snake", "Queen Snake", "Queenly Echo", "LEGENDARY", "L35"),
        AttrDef("unlimited_power", "jormung", "Jormung", "Unlimited Power", "LEGENDARY", "L36"),
        AttrDef("treasure_fisher", "ghost_crab", "Ghost Crab", "Treasure Fisher", "LEGENDARY", "L38"),
        AttrDef("unlimited_energy", "etherdrake", "Etherdrake", "Unlimited Energy", "LEGENDARY", "L39"),
        AttrDef("tough_claws", "grizzly_bear", "Grizzly Bear", "Tough Claws", "LEGENDARY", "L40"),
        AttrDef("ultimate_dna", "galaxy_fish", "Galaxy Fish", "Ultimate DNA", "LEGENDARY", "L41"),
        AttrDef("almighty", "molthorn", "Molthorn", "Almighty Echo", "LEGENDARY", "L42"),
        AttrDef("echo_of_elemental", "starborn", "Starborn", "Echo of Elemental", "LEGENDARY", "L44"),
        AttrDef("cocoon_chance", "primordial", "Primordial", "Cocoon Chance", "LEGENDARY", "L45"),
        AttrDef("groovy_radar", "cocoaleech", "Cocoaleech", "Groovy Radar", "LEGENDARY", "L46"),
        AttrDef("bayou_biter", "titanoboa", "Titanoboa", "Bayou Hook", "LEGENDARY", "L47"),
        AttrDef("miracle_chance", "", "Rainbug", "Miracle Chance", "LEGENDARY", "L49"),
        AttrDef("slayer_discount", "paragon", "Paragon", "Slayer Discount", "LEGENDARY", "L54"),
        AttrDef("greenhouse_speed", "timestalk_clone", "Timestalk Clone", "Greenhouse Speed", "LEGENDARY", "L57"),
        AttrDef("cold_resistance", "wumpa", "Wumpa", "Cold Resistance", "LEGENDARY", "L60"),
        AttrDef("forest_elemental", "sylvan", "Sylvan", "Forest Elemental", "RARE", "R1"),
        AttrDef("torrent_elemental", "cascade", "Cascade", "Torrent Elemental", "RARE", "R2"),
        AttrDef("lightning_elemental", "bolt", "Bolt", "Lightning Elemental", "RARE", "R3"),
        AttrDef("animal_expertise", "bambloom", "Bambloom", "Animal Expertise", "RARE", "R4"),
        AttrDef("frog_legs", "toad", "Toad", "Frog Legs", "RARE", "R5"),
        AttrDef("ice_essence", "glacite_walker", "Glacite Walker", "Essence of Ice", "RARE", "R6"),
        AttrDef("beacon_zealot", "beaconmite", "Beaconmite", "Beacon Zealot", "RARE", "R7"),
        AttrDef("great_karma", "lizard_king", "Lizard King", "Great Karma", "RARE", "R8"),
        AttrDef("hunters_pressure", "python", "Python", "Hunter's Pressure", "RARE", "R9"),
        AttrDef("fancy_visit", "invisibug", "Invisibug", "Fancy Visit", "RARE", "R10"),
        AttrDef("moonglade_serendipity", "piranha", "Piranha", "Moonglade Serendipity", "RARE", "R11"),
        AttrDef("catacomb_box", "hideongeon", "Hideongeon", "Catacombs Box", "RARE", "R13"),
        AttrDef("bone_font", "lapis_skeleton", "Lapis Skeleton", "Bone Font", "RARE", "R15"),
        AttrDef("crop_bug", "cropeetle", "Beetle", "Crop Bug", "RARE", "R16"),
        AttrDef("humanoid_ruler", "drowned", "Drowned", "Undead Fortune", "RARE", "R18"),
        AttrDef("helix_sharpening", "vulture", "Vulture", "Helix Sharpening", "RARE", "R19"),
        AttrDef("atomized_mithril", "star_sentry", "Star Sentry", "Atomized Mithril", "RARE", "R21"),
        AttrDef("kuudra_box", "hideondra", "Hideondra", "Kuudra's Box", "RARE", "R22"),
        AttrDef("dwarven_serendipity", "abyssal_lantern", "Abyssal Lanternfish", "Dwarven Serendipity", "RARE", "R23"),
        AttrDef("spider_essence", "arachne", "Arachne", "Essence of Arthropods", "RARE", "R24"),
        AttrDef("cookie_eater", "bitbug", "Bitbug", "Cookie Eater", "RARE", "R25"),
        AttrDef("crimson_essence", "lava_leech", "Lava Leech", "Essence of Crimson", "RARE", "R26"),
        AttrDef("undead_essence", "revenant", "Revenant", "Essence of Unliving", "RARE", "R27"),
        AttrDef("crystal_serendipity", "silentdepth", "Silentdepth", "Crystal Serendipity", "RARE", "R29"),
        AttrDef("deadeye", "skeletor", "Skeletor", "Deadeye", "RARE", "R30"),
        AttrDef("atomized_crystals", "thyst", "Thyst", "Atomized Crystals", "RARE", "R31"),
        AttrDef("diamond_frog", "sea_shine", "Seashine", "Diamond Frog", "RARE", "R32"),
        AttrDef("quartz_speed", "quartzfang", "Quartzfang", "Quartz Speed", "RARE", "R33"),
        AttrDef("accessory_size", "hideonring", "Hideonring", "Accessory Size", "RARE", "R34"),
        AttrDef("winter_serendipity", "snowfin", "Snowfin", "Winter's Serendipity", "RARE", "R35"),
        AttrDef("lifeline", "kada_knight", "Kada Knight", "Lifeline", "RARE", "R36"),
        AttrDef("chop", "hummingbird", "Hummingbird", "Chop", "RARE", "R37"),
        AttrDef("rabbit_crew", "carrot_king", "Carrot King", "Rabbit Crew", "RARE", "R38"),
        AttrDef("breeze", "wither_specter", "Wither Spectre", "Breeze", "RARE", "R39"),
        AttrDef("battle_tracker", "badger", "Badger", "Battle Tracker", "RARE", "R40"),
        AttrDef("ignition", "matcho", "Matcho", "Ignition", "RARE", "R42"),
        AttrDef("pretty_clothes", "ladybug", "Ladybug", "Visitor Copper", "RARE", "R43"),
        AttrDef("extreme_pressure", "lumisquid", "Lumisquid", "Extreme Pressure", "RARE", "R44"),
        AttrDef("pure_reptile", "crocodile", "Crocodile", "Pure Reptile", "RARE", "R45"),
        AttrDef("animal_fortune", "wild_hog", "Wild Hog", "Animal Fortune", "RARE", "R46"),
        AttrDef("berry_enjoyer", "bullfrog", "Bullfrog", "Berry Enjoyer", "RARE", "R47"),
        AttrDef("forest_essence", "dreadwing", "Dreadwing", "Essence of the Forest", "RARE", "R49"),
        AttrDef("deep_diving", "joydive", "Joydive", "Deep Diving", "RARE", "R50"),
        AttrDef("atomized_glacite", "stalagmight", "Stalagmight", "Atomized Glacite", "RARE", "R51"),
        AttrDef("fungy_luck", "fungloom", "Fungloom", "Fungy Luck", "RARE", "R52"),
        AttrDef("eelastic", "eel", "Eel", "Eelastic", "RARE", "R53"),
        AttrDef("hunters_grasp", "king_cobra", "King Cobra", "Hunter's Grasp", "RARE", "R54"),
        AttrDef("critter_fortune", "hewver", "Hewver", "Critter Fortune", "RARE", "R55"),
        AttrDef("blazing_fortune", "lava_flame", "Lava Flame", "Blazing Fortune", "RARE", "R56"),
        AttrDef("dragon_essence", "draconic", "Draconic", "Essence of Dragons", "RARE", "R57"),
        AttrDef("battle_experience", "falcon", "Falcon", "Battle Experience", "RARE", "R58"),
        AttrDef("crimson_serendipity", "inferno_koi", "Inferno Koi", "Crimson Serendipity", "RARE", "R59"),
        AttrDef("wither_essence", "wither", "Wither", "Essence of Wither", "RARE", "R60"),
        AttrDef("echo_of_sharpening", "gecko", "Gecko", "Echo of Sharpening", "RARE", "R61"),
        AttrDef("construct_fortune", "wiki_tiki", "Wiki Tiki", "Construct Fortune", "RARE", "R62"),
        AttrDef("mythological_fortune", "minotaur", "Minotaur", "Mythological Fortune", "RARE", "R63"),
        AttrDef("cubic_fortune", "hivethief", "Hivethief", "Cubic Fortune", "RARE", "R64"),
        AttrDef("boot_fisher", "maggot", "Maggot", "Boot Fisher", "RARE", "R65"),
        AttrDef("sleepy_spread", "snoozle", "Snoozle", "Sleepy Spread", "RARE", "R66"),
        AttrDef("flying_fortune", "parakeet", "Parakeet", "Flying Fortune", "RARE", "R67"),
        AttrDef("thunder_speed", "thunder", "Thunder", "Thunder Speed", "RARE", "R68"),
        AttrDef("cavernous_tracker", "rockmite", "Rockmite", "Cavernous Tracker", "RARE", "R69"),
        AttrDef("floor_fortune", "anteater", "Anteater", "Floor Fortune", "RARE", "R70"),
        AttrDef("scrap_chance", "scrappy", "Scrappy", "Scrap Chance", "RARE", "R72"),
        AttrDef("elusive_fortune", "hideyho", "Hideyho", "Elusive Fortune", "RARE", "R73"),
        AttrDef("great_treasure", "mantis_shrimp", "Mantis Shrimp", "Great Treasure", "RARE", "R74"),
        AttrDef("subterranean_fortune", "chuckwalla", "Chuckwalla", "Subterranean Fortune", "RARE", "R75"),
        AttrDef("woodland_fortune", "hideonfloor", "Hideonfloor", "Woodland Fortune", "RARE", "R76"),
        AttrDef("greedy_goblin", "gimmiegold", "Gimmiegold", "Greedy Goblin", "RARE", "R77"),
        AttrDef("frozen_fortune", "billygoat", "Billygoat", "Frozen Fortune", "RARE", "R78"),
        AttrDef("arcane_fortune", "hideonwall", "Hideonwall", "Arcane Fortune", "RARE", "R79"),
        AttrDef("underwater_tracker", "nozzlenose", "Nozzlenose", "Underwater Tracker", "RARE", "R80"),
        AttrDef("refined_luck", "stoneworm", "Stoneworm", "Refined Luck", "RARE", "R81"),
        AttrDef("foraging_tracker", "fluffling", "Fluffling", "Foraging Tracker", "RARE", "R82"),
        AttrDef("torrhus_serendipity", "stingray", "Stingray", "Torrhus Serendipity", "RARE", "R83"),
        AttrDef("mutation_serendipity", "zombuddy", "Zombuddy", "Mutation Serendipity", "RARE", "R84"),
        AttrDef("forest_serendipity", "puck", "Puck", "Forest Serendipity", "RARE", "R85"),
        AttrDef("essence_of_fossils", "troodon", "Troodon", "Essence of Fossils", "RARE", "R86"),
        AttrDef("arthropod_fortune", "black_widow", "Black Widow", "Arthropod Fortune", "RARE", "R87"),
        AttrDef("atomized_whispers", "pangolin", "Pangolin", "Atomized Whispers", "RARE", "R88"),
        AttrDef("aquatic_fortune", "giant_water_bug", "Giant Water Bug", "Aquatic Fortune", "RARE", "R89"),
        AttrDef("rekindle", "murkbat", "Murkbat", "Rekindle", "RARE", "R91"),
        AttrDef("echo_of_buckets", "goldolot", "Goldolot", "Echo of Buckets", "RARE", "R92"),
        AttrDef("mythic_rabbit_luck", "rabbit_neighbor", "Rabbit Neighbor", "Mythic Rabbit Luck", "RARE", "R94"),
        AttrDef("first_sweep", "torrid", "Torrid", "First Sweep", "RARE", "R95"),
        AttrDef("axe_cooldown", "drybark", "Drybark", "Axe Cooldown", "RARE", "R97"),
        AttrDef("wood_elemental", "bramble", "Bramble", "Wood Elemental", "UNCOMMON", "U1"),
        AttrDef("pest_cooldown", "moth", "Moth", "Pest Cooldown", "UNCOMMON", "U100"),
        AttrDef("enchanted_farmer", "mosquito", "Mosquito", "Enchanted Farmer", "UNCOMMON", "U103"),
        AttrDef("legendary_rabbit_luck", "rabbit_cat", "Rabbit Cat", "Legendary Rabbit Luck", "UNCOMMON", "U106"),
        AttrDef("water_elemental", "tide", "Tide", "Water Elemental", "UNCOMMON", "U2"),
        AttrDef("stone_elemental", "quake", "Quake", "Stone Elemental", "UNCOMMON", "U3"),
        AttrDef("fig_collector", "sparrow", "Sparrow", "Fig Collector", "UNCOMMON", "U4"),
        AttrDef("gold_bait", "goldfin", "Goldfin", "Gold Bait", "UNCOMMON", "U5"),
        AttrDef("mountain_climber", "troglobyte", "Troglobyte", "Mountain Climber", "UNCOMMON", "U6"),
        AttrDef("bigger_box", "hideoncave", "Hideoncave", "Bigger Box", "UNCOMMON", "U7"),
        AttrDef("good_karma", "salamander", "Salamander", "Good Karma", "UNCOMMON", "U8"),
        AttrDef("echo_of_boxes", "cuboa", "Cuboa", "Echo of Boxes", "UNCOMMON", "U9"),
        AttrDef("pest_luck", "pest", "Field Mouse", "Pest Luck", "UNCOMMON", "U10"),
        AttrDef("forest_trap", "mossybit", "Mossybit", "Forest Trap", "UNCOMMON", "U11"),
        AttrDef("mana_steal", "rain_slime", "Rain Slime", "Mana Steal", "UNCOMMON", "U12"),
        AttrDef("humanoid_ruler_new", "wetwing", "Wetwing", "Humanoid Ruler", "UNCOMMON", "U14"),
        AttrDef("dragon_shortbow_improvement", "seer", "Seer", "Dragon Shortbow Improvement", "UNCOMMON", "U15"),
        AttrDef("mangrove_sharpening", "heron", "Heron", "Mangrove Sharpening", "UNCOMMON", "U16"),
        AttrDef("witchs_fortune", "sea_witch", "Sea Witch", "Witch's Fortune", "UNCOMMON", "U17"),
        AttrDef("speed", "obsidian_defender", "Obsidian Defender", "Speed", "UNCOMMON", "U18"),
        AttrDef("pest_fortune", "cricket", "Cricket", "Pest Fortune", "UNCOMMON", "U19"),
        AttrDef("lost_and_found", "salmon", "Salmon", "Lost and Found", "UNCOMMON", "U20"),
        AttrDef("hunters_fangs", "viper", "Viper", "Hunter's Fang", "UNCOMMON", "U21"),
        AttrDef("insect_power", "praying_mantis", "Praying Mantis", "Pest Ruler", "UNCOMMON", "U22"),
        AttrDef("lily_tracker", "lotum", "Lotum", "Lily Tracker", "UNCOMMON", "U23"),
        AttrDef("undead", "zombie_soldier", "Zombie Soldier", "Undead Ruler", "UNCOMMON", "U24"),
        AttrDef("strong_arms", "bambuleaf", "Bambuleaf", "Strong Arms", "UNCOMMON", "U25"),
        AttrDef("dwarven_training", "treasure_hoarder", "Treasure Hoarder", "Dwarven Training", "UNCOMMON", "U26"),
        AttrDef("life_recovery", "sycophant", "Sycophant", "Life Recovery", "UNCOMMON", "U27"),
        AttrDef("mangrove_collector", "seagull", "Seagull", "Mangrove Collector", "UNCOMMON", "U28"),
        AttrDef("spirit_axe", "ent", "Ent", "Woodland Ruler", "UNCOMMON", "U29"),
        AttrDef("combo", "soul_of_the_alpha", "Soul of the Alpha", "Combo", "UNCOMMON", "U30"),
        AttrDef("strong_legs", "mochibear", "Mochibear", "Strong Legs", "UNCOMMON", "U31"),
        AttrDef("infection", "magma_slug", "Magma Slug", "Infection", "UNCOMMON", "U32"),
        AttrDef("arachno", "flaming_spider", "Flaming Spider", "Arthropod Ruler", "UNCOMMON", "U33"),
        AttrDef("kat_favorite", "kiwi", "Kiwi", "Kat's Favorite", "UNCOMMON", "U34"),
        AttrDef("ender", "bruiser", "Zealot Bruiser", "Ender Ruler", "UNCOMMON", "U36"),
        AttrDef("magmatic_ruler", "strider_surfer", "Stridersurfer", "Magmatic Ruler", "UNCOMMON", "U38"),
        AttrDef("battle_frog", "rana", "Rana", "Battle Frog", "UNCOMMON", "U39"),
        AttrDef("infiltration", "termite", "Earthworm", "Infiltration", "UNCOMMON", "U40"),
        AttrDef("golden_frog", "flip_flopper", "Flipflopper", "Golden Frog", "UNCOMMON", "U41"),
        AttrDef("frozen_ruler", "polaris", "Polaris", "Frozen Ruler", "UNCOMMON", "U42"),
        AttrDef("foraging_frog", "treefrog", "Treefrog", "Foraging Frog", "UNCOMMON", "U43"),
        AttrDef("compost_speed", "bayou_sludge", "Bayou Sludge", "Compost Speed", "UNCOMMON", "U44"),
        AttrDef("battle_arachnid", "areita", "Areita", "Battle Arachnid", "UNCOMMON", "U45"),
        AttrDef("airborne_ruler", "bluebird", "Bluebird", "Airborne Ruler", "UNCOMMON", "U46"),
        AttrDef("flexible_fisher", "osedax", "Osedax", "Flexible Fisher", "UNCOMMON", "U47"),
        AttrDef("arcane_ruler", "duplico", "Duplico", "Arcane Ruler", "UNCOMMON", "U48"),
        AttrDef("buckle_fisher", "litterbug", "Litterbug", "Buckle Fisher", "UNCOMMON", "U49"),
        AttrDef("titanoboa_tracker", "water_snake", "Water Snake", "Titanoboa Tracker", "UNCOMMON", "U50"),
        AttrDef("zealot_tracker", "gazer", "Gazer", "Zealot Tracker", "UNCOMMON", "U51"),
        AttrDef("visitor_honey", "honeybug", "Honeybug", "Visitor Honey", "UNCOMMON", "U52"),
        AttrDef("yeti_tracker", "shuddersquid", "Shuddersquid", "Yeti Tracker", "UNCOMMON", "U53"),
        AttrDef("soul_snatcher", "solsnatcher", "Solsnatcher", "Soul Snatcher", "UNCOMMON", "U55"),
        AttrDef("bucket_greed", "sepialot", "Sepialot", "Bucket Greed", "UNCOMMON", "U56"),
        AttrDef("honey_serendipity", "honey_badger", "Honey Badger", "Honey Serendipity", "UNCOMMON", "U57"),
        AttrDef("subterranean_ruler", "driftling", "Driftling", "Subterranean Ruler", "UNCOMMON", "U58"),
        AttrDef("lily_puncher", "tewtil", "Tewtil", "Lily Puncher", "UNCOMMON", "U59"),
        AttrDef("mythological_ruler", "minos_hunter", "Minos Hunter", "Mythological Ruler", "UNCOMMON", "U60"),
        AttrDef("builder_discount", "woodchucker", "Woodchucker", "Builder Discount", "UNCOMMON", "U61"),
        AttrDef("starlyn_training", "solar", "Solar", "Starlyn Training", "UNCOMMON", "U62"),
        AttrDef("visitor_compost", "parched", "Parched", "Visitor Compost", "UNCOMMON", "U63"),
        AttrDef("bartender_discount", "bloodbat", "Bloodbat", "Bartender Discount", "UNCOMMON", "U64"),
        AttrDef("combat_trap", "dustybit", "Dustybit", "Combat Trap", "UNCOMMON", "U65"),
        AttrDef("visitor_cheese", "woodlouse", "Woodlouse", "Visitor Cheese", "UNCOMMON", "U67"),
        AttrDef("galatea_training", "ember", "Ember", "Galatea Training", "UNCOMMON", "U68"),
        AttrDef("bayou_treasure", "cheeky_tiki", "Cheeky Tiki", "Bayou Treasure", "UNCOMMON", "U69"),
        AttrDef("visitor_plant", "red_panda", "Red Panda", "Visitor Plant", "UNCOMMON", "U70"),
        AttrDef("animal_ruler", "sprawl", "Sprawl", "Animal Ruler", "UNCOMMON", "U71"),
        AttrDef("tiki_tracker", "sneaky_tiki", "Sneaky Tiki", "Tiki Tracker", "UNCOMMON", "U72"),
        AttrDef("construct_ruler", "shrieky_tiki", "Shrieky Tiki", "Construct Ruler", "UNCOMMON", "U75"),
        AttrDef("forest_felling", "woodpecker", "Woodpecker", "Helix Timber", "UNCOMMON", "U76"),
        AttrDef("mite_spawner", "honeymite", "Honeymite", "Mite Spawner", "UNCOMMON", "U78"),
        AttrDef("elusive_ruler", "queen_ant", "Queen Ant", "Elusive Ruler", "UNCOMMON", "U79"),
        AttrDef("helix_collector", "hawk", "Hawk", "Helix Collector", "UNCOMMON", "U82"),
        AttrDef("ticket_discount", "june_bug", "June Bug", "Ticket Discount", "UNCOMMON", "U85"),
        AttrDef("visitor_dung", "dung_beetle", "Dung Beetle", "Visitor Dung", "UNCOMMON", "U88"),
        AttrDef("sprayonator_serendipity", "rat", "Rat", "Sprayonator Serendipity", "UNCOMMON", "U91"),
        AttrDef("bonus_pest_chance", "keeled_slug", "Keeled Slug", "Bonus Pest Chance", "UNCOMMON", "U94"),
        AttrDef("filter_upgrade", "mite", "Mite", "Filter Upgrade", "UNCOMMON", "U97"),
    )
}
